CREAR TABLA


ANADIR COLUMNA
ALTER TABLE datospersonales ADD COLUMN EDAD INT(2);

BORRAR COLUMNA
ALTER TABLE DATOSPERSONALES DROP EDAD;

INTRODUCIR REGISTRO. INDICO TODOS LOS CAMPOS QUE VOY A RELLENAR Y LUEGO EN VALUES DOY VALORES EN ORDEN
INSERT INTO DATOSPERSONALES (NIF, NOMBRE, APELLIDO, EDAD) VALUES ("33434434", "jOSE", "RODRIGUEZ", 23); 